INSERT INTO `library`.`author` (`fio`, `birthday`) VALUES ('Дем Михайлов', '1973-04-12');
INSERT INTO `library`.`author` (`fio`, `birthday`) VALUES ('Андрей Васильев', '1979-09-23');
INSERT INTO `library`.`author` (`fio`, `birthday`) VALUES ('Артем Каменистый', '1982-10-19');
INSERT INTO `library`.`author` (`fio`, `birthday`) VALUES ('Василий Маханенко', '1976-11-20');
INSERT INTO `library`.`author` (`fio`, `birthday`) VALUES ('Джефф Сазерленд', '1983-03-16');
INSERT INTO `library`.`author` (`fio`, `birthday`) VALUES ('Дмитрий Зурков', '1969-05-21');
INSERT INTO `library`.`author` (`fio`, `birthday`) VALUES ('Макс Глебов', '1987-03-12');
INSERT INTO `library`.`author` (`fio`, `birthday`) VALUES ('Орсон Скотт Кард', '1988-06-26');
INSERT INTO `library`.`author` (`fio`, `birthday`) VALUES ('Сергей Тармашев', '1975-09-11');
INSERT INTO `library`.`author` (`fio`, `birthday`) VALUES ('Эл Робертсон', '1972-07-06');
